ci: fixup cloudbuild.yaml again
CI is failing cause of
ERROR: failed to build: name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE
Changes cloudbuild to reference IMG_REGISTRY instead. The image name will now be "controller".

Signed-off-by: Max Cao <macao@redhat.com>